name: Update GEX Dashboard

on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes
  workflow_dispatch:      # Allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Run GEX Script
        env:
          TRADIER_TOKEN: ${{ secrets.TRADIER_TOKEN }}
          APPS_SCRIPT_URL: ${{ secrets.APPS_SCRIPT_URL }} # <--- ADD THIS LINE
        run: python gex_engine.py
